// @koala-prepend  '../bower_components/outlayer/outlayer.js'
// @koala-append  '../bower_components/angular/angular.js'
// @koala-append  '../bower_components/angular-masonry/angular-masonry.js'
// @koala-append  '../bower_components/angular-resource/angular-resource.js'
// @koala-append  '../bower_components/angular-route/angular-route.js'
// @koala-append  '../bower_components/ng-dialog/js/ngDialog.js'
// @koala-append  'prettify/prettify.js'
// @koala-append  'prettify/lang-css.js'
